Name: ${APPLICATION_NAME}
Description: The BigObjects API
Version: ${APPLICATION_VERSION}
Libs: -Wl,-R${LIB_INSTALL_DIR} -L${LIB_INSTALL_DIR} -lbigobjects
Cflags: -I${INCLUDE_INSTALL_DIR} -D_FILE_OFFSET_BITS=64 -D__USE_FILE_OFFSET64
